image: docker:latest

stages:
  - build-docker

# Build docker
build_docker:dockerhub:arm32v6:
  image: docker:latest
  stage: build-docker
  tags:
    - armv6
    - shell
  only:
    - master
  cache: {}
  variables:
    IMAGE_TAG: samibourouis/rpi-chronograf:arm32v6
  before_script:
    - docker info
    - echo $CI_BUILD_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  script:
    - docker build --no-cache -t $IMAGE_TAG .
    - BALENA_CLI_VERSION=`docker run -i $IMAGE_TAG balena version`
    - docker tag $IMAGE_TAG $IMAGE_TAG-$BALENA_CLI_VERSION
    - docker push $IMAGE_TAG-$BALENA_CLI_VERSION
