image: docker:latest

stages:
  - build-docker
  - publish-git

# Build docker
build_docker:arm32v6:
  image: docker:latest
  stage: build-docker
  tags:
    - armv6
    - shell
  only:
    - master
  variables:
    IMAGE_TAG: samibourouis/rpi-chronograf:arm32v6
  before_script:
    - docker info
  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker build -t ${IMAGE_TAG} .
    - docker push ${IMAGE_TAG}

# Publish to Github
github_mirror:
  stage: publish-git
  image:
    name: alpine/git
    entrypoint: [ "/bin/sh", "-c" ]
  only:
    - master
  variables:
    GIT_STRATEGY: clone
    GIT_CHECKOUT: "false"
  script: |
    cd /tmp
    git clone --mirror ${CI_REPOSITORY_URL} project
    cd project
    git remote add github https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/samibourouis/rpi-chronograf.git
    git push --mirror github
